import { useState } from 'react';
import { OperationalWorkspace } from '../../app/workspace/OperationalWorkspace';
import { fundicaoDcIdealCycleTimeSecondsFixture } from '../../demo/fixtures/fundicaoDcIdealCycleTime';
import { fundicaoDcMoldsFixture } from '../../demo/fixtures/fundicaoDcMolds';
import { fundicaoDcProductionReportsFixture } from '../../demo/fixtures/fundicaoDcProductionReports';
import { selectProductionExecutions, selectProductionScheduling, selectScenarioDefinition, useScenarioStore } from '../../demo/scenario-engine/scenarioStore';
import { operationalFactOriginLabel, type OperationalFactOrigin } from '../../domain/automation/models';
import { classifyMoldLife, moldForResource } from '../../domain/mold/models';
import type { DemonstrativePauseReason, ProductionExecutionStatus } from '../../domain/production-execution/models';
import { assessLotExecutionHealth } from '../../domain/production-execution/lotHealth';
import { reportsForLot } from '../../domain/production-execution/productionReport';
import { FOUNDRY_RESOURCE_IDS } from '../../domain/resource/models';
import { Bar } from '../../shared/ui/Bar/Bar';
import { Button } from '../../shared/ui/Button/Button';
import { IconTip } from '../../shared/ui/IconTip/IconTip';
import { LotHealthIndicator } from '../../shared/ui/LotHealthIndicator/LotHealthIndicator';
import { formatTime } from '../production-scheduling/productionSchedulingViewModel';
import styles from './ProductionExecutionPage.module.css';

const statusLabel: Record<ProductionExecutionStatus, string> = { NOT_STARTED: 'Aguardando início', IN_PROGRESS: 'Em produção', PAUSED: 'Pausada', COMPLETED: 'Concluída' };
const reasonLabel: Record<DemonstrativePauseReason, string> = { MATERIAL_SHORTAGE: 'Falta de material', MACHINE_ADJUSTMENT: 'Ajuste de máquina', TOOLING: 'Ferramental', QUALITY: 'Qualidade', OTHER: 'Outro' };
const moldStatusLabel = { NORMAL: 'Normal', ATTENTION: 'Atenção', MAINTENANCE_RECOMMENDED: 'Manutenção recomendada' } as const;
const originIcon: Record<OperationalFactOrigin, string> = { AUTOMATION: '⚙', OPERATOR: '✎', MES: '▤', EXTERNAL_SYSTEM: '↔' };

export function ProductionExecutionPage() {
  const definition = useScenarioStore(selectProductionScheduling);
  const scenario = useScenarioStore(selectScenarioDefinition);
  const executions = useScenarioStore(selectProductionExecutions);
  const pause = useScenarioStore((state) => state.pauseLotExecution); const resume = useScenarioStore((state) => state.resumeLotExecution); const complete = useScenarioStore((state) => state.completeLotExecution); const update = useScenarioStore((state) => state.updateLotProducedQuantity); const start = useScenarioStore((state) => state.startLotExecution);
  const [pauseReasons, setPauseReasons] = useState<Record<string, DemonstrativePauseReason>>({});
  if (!definition || !scenario) return <p>Preparando execução demonstrativa…</p>;
  return <OperationalWorkspace perspective="EXECUTION" sidebarContent={<div className={styles.sidebar}><strong>Situação atual</strong><span>● Em produção</span><span>Ⅱ Pausada</span><span>✓ Concluída</span><span>○ Aguardando</span><small>Horário atual único: {formatTime(scenario.currentScenarioTime)}</small></div>}>
    <div className={styles.page}><header className={styles.hero}><div><span>Capability 05 · Core</span><h1>O que está sendo executado agora?</h1><p>Produção real demonstrativa por Recurso · Horário atual {formatTime(scenario.currentScenarioTime)}</p></div><aside><strong>Cenário demonstrativo</strong><span>Execução não representa quantidade boa, disponível ou aceita pela Qualidade.</span></aside></header>
    <section className={styles.executionBoard} aria-label="Situação das cinco máquinas">{FOUNDRY_RESOURCE_IDS.map((resourceId) => { const record = Object.values(executions).find((item) => item.resourceId === resourceId); const lot = record ? definition.lots.find((item) => item.id === record.lotId) : undefined; const material = lot ? definition.materials.find((item) => item.id === lot.materialId) : undefined; const order = lot ? definition.productionOrders.find((item) => item.id === lot.productionOrderId) : undefined; const nextLot = definition.lots.filter((item) => item.scheduledResourceId === resourceId && (!lot || Date.parse(item.scheduledStart) > Date.parse(lot.scheduledStart))).sort((a,b) => Date.parse(a.scheduledStart)-Date.parse(b.scheduledStart))[0]; const mold = moldForResource(fundicaoDcMoldsFixture, resourceId); const moldStatus = mold ? classifyMoldLife(mold.lifeUsedRatio) : undefined; const reports = record ? reportsForLot(fundicaoDcProductionReportsFixture, record.lotId) : []; const latestApontamento = reports[0]; const cycleTimeSeconds = lot ? fundicaoDcIdealCycleTimeSecondsFixture[lot.materialId] : undefined; const health = record && lot ? assessLotExecutionHealth(record, lot.scheduledStart, lot.scheduledFinish, cycleTimeSeconds, scenario.currentScenarioTime) : null; return <article key={resourceId} data-status={record?.status ?? 'NOT_STARTED'}><header><strong>{resourceId}</strong>{health && lot && material ? <LotHealthIndicator health={health} context={{ lotLabel: String(lot.lotNumber), material: material.name, quantity: lot.quantity, resourceId, scheduledStart: formatTime(lot.scheduledStart), scheduledFinish: formatTime(lot.scheduledFinish) }} compact /> : null}<span>{record ? statusLabel[record.status] : 'Sem execução atual'}</span></header>{record && lot && material ? <><div className={styles.primary}><div><small>Lote atual</small><b>Lote {lot.lotNumber}</b><span>{material.name} · OP {order?.orderNumber}</span></div><div className={styles.quantity}><strong>{record.producedQuantity}</strong><span>/ {record.plannedQuantity} peças</span><small>Produzido / Planejado</small></div></div>
{mold ? <div className={styles.moldLine} data-tone={moldStatus}><IconTip icon="⚙" label="Molde instalado" value={mold.code} tip={`Molde ${mold.code} · ${Math.round(mold.lifeUsedRatio*100)}% da vida útil demonstrativa`} /><Bar ratio={mold.lifeUsedRatio} tone={moldStatus === 'NORMAL' ? 'positive' : 'attention'} label={`Vida útil do molde: ${Math.round(mold.lifeUsedRatio*100)}%`} className={styles.moldBar} />{moldStatus !== 'NORMAL' ? <span>{moldStatusLabel[moldStatus!]}</span> : null}</div> : null}
<section className={styles.reportBlock} aria-label={`Apontamento da produção — ${resourceId}`}>
  <strong>Apontamento da produção</strong>
  {latestApontamento ? <p className={styles.reportLatest}><IconTip icon={originIcon[latestApontamento.origin]} label="Último apontamento" value={`+${latestApontamento.quantity} peças`} tip={`${operationalFactOriginLabel[latestApontamento.origin]} · ${formatTime(latestApontamento.reportedAt)}`} /><span>{formatTime(latestApontamento.reportedAt)}</span></p> : <p className={styles.reportLatest}>Nenhum apontamento registrado ainda.</p>}
  {reports.length > 0 ? <details className={styles.reportHistory}><summary>Histórico de apontamentos <span>Ver histórico</span></summary>{reports.map((entry, index) => <p key={index}>{formatTime(entry.reportedAt)} · +{entry.quantity} · {operationalFactOriginLabel[entry.origin]}</p>)}</details> : null}
</section>
<dl><div><dt>Início planejado</dt><dd>{formatTime(record.scheduledStart)}</dd></div><div><dt>Início real</dt><dd>{record.actualStart ? formatTime(record.actualStart) : '—'}</dd></div><div><dt>Responsável</dt><dd>{record.executedBy ?? '—'}</dd></div><div><dt>Versão do plano</dt><dd>{record.scheduleVersionId}</dd></div></dl>{record.status === 'PAUSED' ? <p className={styles.pauseReason}><strong>Motivo:</strong> {reasonLabel[record.pauses.at(-1)?.reason ?? 'OTHER']} · desde {formatTime(record.pauses.at(-1)!.pausedAt)}</p> : null}<div className={styles.actions}>{record.status === 'NOT_STARTED' ? <Button onClick={() => start(record.lotId)}>Iniciar produção</Button> : null}{record.status === 'IN_PROGRESS' || record.status === 'PAUSED' ? <label>Quantidade produzida<input aria-label={`Quantidade produzida na ${resourceId}`} type="number" min="0" value={record.producedQuantity} onChange={(event) => update(record.lotId, Number(event.target.value))} /></label> : null}{record.status === 'IN_PROGRESS' ? <><label>Motivo da pausa<select aria-label={`Motivo da pausa na ${resourceId}`} value={pauseReasons[record.lotId] ?? 'MACHINE_ADJUSTMENT'} onChange={(event) => setPauseReasons((values) => ({ ...values, [record.lotId]: event.target.value as DemonstrativePauseReason }))}>{Object.entries(reasonLabel).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><Button onClick={() => pause(record.lotId, pauseReasons[record.lotId] ?? 'MACHINE_ADJUSTMENT')}>Pausar</Button><Button onClick={() => complete(record.lotId)}>Concluir</Button></> : null}{record.status === 'PAUSED' ? <Button onClick={() => resume(record.lotId)}>Retomar</Button> : null}</div></> : <p className={styles.waiting}>Aguardando trabalho liberado.</p>}<footer><small>Próxima produção conhecida</small><strong>{nextLot ? `Lote ${nextLot.lotNumber} · ${formatTime(nextLot.scheduledStart)}` : 'Sem próxima produção no período'}</strong></footer></article>; })}</section>
    <section className={styles.chain}><strong>Plano</strong><span>→</span><strong>Liberação</strong><span>→</span><b>Execução</b><span>→</span><em>Eventos</em><span>→</span><em>Produção real</em><span>→</span><em>Qualidade / Perdas</em><span>→</span><em>OEE</em></section></div>
  </OperationalWorkspace>;
}
