import type { BufferPosition, Lot, Material } from '../../../domain/production-scheduling/models';
import styles from '../ProductionSchedulingPage.module.css';

export const BUFFER_CRITICAL_LOT_ID = 'lot-255';
export const BUFFER_CRITICAL_CONTRIBUTION_DAYS = 0.2;

export function BufferDecisionSupport({ position, material, criticalLot, simulationActive, hasConflict }: { position: BufferPosition; material: Material; criticalLot?: Lot; simulationActive: boolean; hasConflict: boolean }) {
  const simulated = position.projectedCoverageDays;
  return <section className={styles.bufferDecision} aria-labelledby="buffer-decision-title"><header><div><small>Critério operacional demonstrativo</small><h2 id="buffer-decision-title">Cobertura do buffer</h2></div><strong>Meta demonstrativa · {position.targetCoverageDays.toLocaleString('pt-BR')} dias</strong></header><dl><div><dt>Atual</dt><dd>{position.currentCoverageDays.toLocaleString('pt-BR')} dias</dd></div><div><dt>Meta demonstrativa</dt><dd>{position.targetCoverageDays.toLocaleString('pt-BR')} dias</dd></div><div><dt>Projetada baseline</dt><dd>{position.projectedCoverageDays.toLocaleString('pt-BR')} dias</dd></div><div><dt>Projetada com simulação</dt><dd>{simulated.toLocaleString('pt-BR')} dias</dd></div><div><dt>Δ para meta</dt><dd>{(simulated - position.targetCoverageDays) >= 0 ? '+' : ''}{(simulated - position.targetCoverageDays).toLocaleString('pt-BR')} dia</dd></div></dl><div className={styles.bufferTrajectory} role="img" aria-label={`Cobertura do buffer ao longo do dia: 2,4 dias às 00h, 2,6 às 07h, 2,8 às 15h e ${position.projectedCoverageDays.toLocaleString('pt-BR')} às 24h; meta ${position.targetCoverageDays.toLocaleString('pt-BR')} dias`}><span style={{ height: '30%' }}><b>00h</b><i>2,4</i></span><span style={{ height: '48%' }}><b>07h</b><i>2,6</i></span><span style={{ height: '66%' }}><b>15h</b><i>2,8</i></span><span style={{ height: '90%' }}><b>24h</b><i>{position.projectedCoverageDays.toLocaleString('pt-BR')}</i></span><em style={{ bottom: `${(position.targetCoverageDays / 3.4) * 100}%` }}>Meta {position.targetCoverageDays.toLocaleString('pt-BR')}</em></div><p><strong>{material.name}</strong>{criticalLot ? <> · Lote {criticalLot.lotNumber} <b>BUFFER-CRITICAL</b> · contribuição demonstrativa +{BUFFER_CRITICAL_CONTRIBUTION_DAYS.toLocaleString('pt-BR')} dia · sem o Lot: 2,9 dias</> : null}{simulationActive ? <span>{hasConflict ? ' · RISCO PARA META DO BUFFER' : ' · impacto direto da movimentação: NEUTRO'}</span> : null}</p></section>;
}
