import type { Lot } from '../../../domain/production-scheduling/models';
import type { LotReadinessAssessment } from '../../../domain/production-readiness/models';
import { FOUNDRY_RESOURCE_IDS, type FoundryResourceId } from '../../../domain/resource/models';
import type { ResourceSimulationImpact } from '../../../domain/production-scheduling/resourceSimulation';
import { Button } from '../../../shared/ui/Button/Button';
import styles from '../ProductionSchedulingPage.module.css';

const statusLabel = { READY: 'Com condição', ATTENTION: 'Atenção', BLOCKED: 'Sem condição', UNKNOWN: 'Desconhecido' } as const;

export function SimulationWorkspace({ active, selectedLot, readiness, impact, comparing, alreadyReleased, locked, onActivate, onSimulate, onUndo, onDiscard, onCompare, onAdopt }: { active: boolean; selectedLot: Lot | null; readiness?: LotReadinessAssessment; impact: ResourceSimulationImpact | null; comparing: boolean; alreadyReleased?: boolean; locked?: boolean; onActivate: () => void; onSimulate: (resourceId: FoundryResourceId) => void; onUndo: () => void; onDiscard: () => void; onCompare: () => void; onAdopt: () => void }) {
  if (!active) return <Button onClick={onActivate}><span aria-hidden="true">◇</span> Avaliar cenário</Button>;
  return <section className={styles.simulationWorkspace} aria-label="Avaliação de cenário"><header><div><strong>AVALIAR CENÁRIO</strong><span>{impact ? '1 movimentação' : '0 alterações'}</span></div><div><Button disabled={!impact} onClick={onCompare}>Comparar</Button><Button onClick={onDiscard}>Encerrar avaliação</Button></div></header>{selectedLot && locked ? <p className={styles.adoptWarning}>Lote {selectedLot.lotNumber} já iniciado/pausado/concluído — programação operacional bloqueada para execução em andamento.</p> : selectedLot && readiness ? <div className={styles.keyboardTargets}><strong>Lote {selectedLot.lotNumber} · {selectedLot.quantity} peças</strong><span>Programação atual: {selectedLot.scheduledResourceId}. Selecione uma alternativa.</span><div>{FOUNDRY_RESOURCE_IDS.map((resourceId) => { const resource = readiness.resources.find((item) => item.resourceId === resourceId)!; const invalid = !resource.eligible || resource.status === 'BLOCKED' || resourceId === selectedLot.scheduledResourceId; return <Button key={resourceId} disabled={invalid} onClick={() => onSimulate(resourceId)}><b>{resourceId}</b><small>{resourceId === selectedLot.scheduledResourceId ? 'Programada · ' : ''}{resource.eligible ? statusLabel[resource.status] : 'Não elegível'}</small></Button>; })}</div></div> : <p>Selecione um Lote para avaliar outra máquina ou horário.</p>}{impact ? <div className={styles.simulationSummary}><dl><div><dt>Programação atual</dt><dd>{impact.originalResourceId}</dd></div><div><dt>Nova programação</dt><dd>{impact.simulatedResourceId}</dd></div><div><dt>Setup origem</dt><dd>{impact.originSetupDeltaMinutes > 0 ? '+' : ''}{impact.originSetupDeltaMinutes} min</dd></div><div><dt>Setup destino</dt><dd>{impact.destinationSetupDeltaMinutes > 0 ? '+' : ''}{impact.destinationSetupDeltaMinutes} min</dd></div><div><dt>Setup líquido</dt><dd>{impact.netSetupDeltaMinutes > 0 ? '+' : ''}{impact.netSetupDeltaMinutes} min</dd></div><div><dt>Conflitos</dt><dd>{impact.conflictLotIds.length}</dd></div><div><dt>Buffer</dt><dd>3,1 → 3,1 dias</dd></div><div><dt>Meta</dt><dd>3,0 dias</dd></div></dl><div className={styles.adoptRow}><Button onClick={onUndo}>Desfazer</Button><Button disabled={locked} onClick={onAdopt}>Confirmar nova programação</Button>{alreadyReleased ? <span className={styles.adoptWarning}>Lote já liberado na máquina programada — revisar Liberação após confirmar.</span> : null}</div>{comparing ? <section className={styles.simulationComparison} aria-label="Comparação Plano recebido versus Simulação"><h3>Plano recebido versus Simulação</h3><p>Máquina original: {impact.originalResourceId} · Máquina simulada: {impact.simulatedResourceId} · Setup Δ {impact.netSetupDeltaMinutes} min · Conflitos: {impact.conflictLotIds.length} · Lotes impactados: {impact.conflictLotIds.length + 1} · Buffer baseline/simulado: 3,1/3,1 dias · Δ meta +0,1 dia.</p></section> : null}</div> : null}</section>;
}
